name: Build with Webpack and deploy to Github Pages
on: push

jobs:
  build-and-deploy:
    name: Build and deploy to gh-pages
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Build for production
        run: npm run build
      
     - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
